add the security lifecycle big picture diagram to getting started
mitre/mitre-saf pull request #388
Opened 2022-08-11 22:26 UTC by em-c-rod

Signed-off-by: Emily Rodriguez <ecrodriguez@mm279976-pc.lan>

2022-08-12 17:32 UTC, wdower commented
Can you make the background on the image transparent? I think you can do that while you export from Powerpoint. 

You'd actually need to make two versions, one with white text and one with dark text, so that it works in both light and dark modes, and then have Vue serve one or the other depending on the light/dark toggle.

2022-08-12 19:08 UTC, Amndeep7 commented
I think it's fine for right now to just paste the graphic, but we should make sure to have some more text either above it or as a description for the graphic to explain it as an accessibility concern.

2022-08-12 19:08 UTC, Amndeep7 requested changes
I think it's fine for right now to just paste the graphic, but we should make sure to have some more text either above it or as a description for the graphic to explain it as an accessibility concern.

2022-08-19 01:03 UTC, wdower reviewed
Image works to start as we discussed, but can we get a higher-res export of it? Looks fuzzy to me on my monitor at 1920x1200

2022-08-19 17:33 UTC, ejaronne commented
The Plan column seems a bit developing-of-STIGs-focused. Recommend change "Develop STIGs from SRGs" to "Choose, tailor, and create security guidance appropriate for your mission"

2022-08-24 21:15 UTC, aaronlippold commented
Looks good with update rez

2022-08-25 03:38 UTC, Amndeep7 commented on src/assets/data/resources.json
> +      "name": "SAF Tooling at a Glance",
I could go either way on this one.  Do either of @wdower or @em-c-rod feel strongly one way or the other?

2022-08-25 03:42 UTC, Amndeep7 commented
> The Plan column seems a bit developing-of-STIGs-focused. Recommend change "Develop STIGs from SRGs" to "Choose, tailor, and create security guidance appropriate for your mission"

@ejaronne This is just a copy paste of the slide graphic so making adjustments esp with that much additional text is hard.  For now we do have the bottom half of that column which mentions pre-existing benchmarks, etc.

2022-08-25 14:54 UTC, Amndeep7 approved these changes

2022-08-25 15:58 UTC, merged